GET http://localhost:4000/user-api/getusers

###
POST http://localhost:4000/user-api/loginuser
Content-Type: application/json

{
    "username":"ravi",
    "password":"ravi"
}

###
POST  http://localhost:4000/user-api/create-user
Content-Type: application/json

{
    "username":"ravi",
    "password":"ravi",
    "city":"hyderabad",
    "email":"ravidurgaprasad9876@gmail.com"
}

###
PUT http://localhost:4000/user-api/update-user

###
DELETE htpp://localhost:4000/user-api/remove-user
